### ISSUE TITLE
Connect to WiFi network without SSID broadcast 

### ISSUE THREAD

**Issue by kisst** [EverythingSmartHome/everything-presence-one#106]
When the SSID isn't broadcasted ( aka it's hidden) the Everything Presence One does not connect to the WiFi network, all other WiFi device I have had no trouble with it and now I had to change the WiFi only for this, it would be nice if I can get back to "normal"

**Comment by EverythingSmartHome** [comment]
This is a standard ESPHome featured as described here under "fast_connect": https://esphome.io/components/wifi.html#configuration-variables

The EP1 has a substitution built in to allow you to modify this behaviour easily, you just need to add the hidden_ssid parameter to your substitutions section:

```
substitutions:
  name: "everything-presence-one"
  friendly_name: "Everything Presence One"
  ...
  hidden_ssid: "true"
  ```
