### ISSUE TITLE
Entity names not using configured name substitution 

### ISSUE THREAD

**Issue by dan-s-github** [EverythingSmartHome/everything-presence-one#129]
Unfortunately I don't know if this a new behaviour, as I didn't check states for a while

I use following es-home configuration:

```
substitutions:
  name: "everything-presence-one-attic"
  friendly_name: "ep1 attic"
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

but the sensors now mostly ignore the name specified

![Screenshot 2024-01-07 at 15 15 23](https://github.com/EverythingSmartHome/everything-presence-one/assets/20974454/d3f6caa6-b91d-4bfe-87ad-a926cfb06f36)

interestingly there are still some that have the -attic postfix

![image](https://github.com/EverythingSmartHome/everything-presence-one/assets/20974454/73787cb7-14af-4e5e-b17b-d062aec0d340)

Not sure if it is HA related or not
