### ISSUE TITLE
With bluetooth enabled since last update 2023.12.8 causes devices to go into boot loop

### ISSUE THREAD

**Issue by pshempel** [EverythingSmartHome/everything-presence-one#141]
Using the below config:
```
packages:
    Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
   # esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
  
dashboard_import:
    package_import_url: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
    
 
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"
  
  esp32_ble_tracker:
 scan_parameters:
   interval: 1100ms
   window: 1100ms 
   active: True
  
bluetooth_proxy:
    active: true
    
   
```
Will constantly reboot, the logs show:

```
[14:18:47][C][api:142]:   Using noise encryption: YES
[14:18:47][C][improv_serial:032]: Improv Serial:
[14:18:49][D][esp32_ble:255]: Disabling BLE...

][W][ota:107]: Last Boot was an unhandled reset, will proceed to safe mode in 1 restarts
```

Then reboots, and you will have to physically pull the power and start it again

**Comment by isewise** [comment]
I'm also having this issue. As of right now I have commented out anything pertaining to BLE on the EP1 and it seems to be okay right now.

**Comment by EverythingSmartHome** [comment]
This unfortunately started in ESPHome 2023.12.6 I believe (at least that's when we started getting reports) - this would need to be resolved upstream in ESPHome, the EP1 config hasn't changed. Bluetooth isn't enabled in supported config options and there is no issues there, it's just when you are running a custom config with Bluetooth added.

You could also try switching the framework to esp-idf rather than Arduino which is generally recommend for anything Bluetooth

**Comment by pshempel** [comment]
So, the strange thing is.  I do not want to point fingers at each project's code, I know the code before the last update of ESPhome had no issues, but the last update, broke things 
Now I do recall, that you had stated at one time that there would be bluethooth at some point, not that it has been an out-of-the-box experience.  

This setup is configured on other ESP32s I use, they are not having this issue. I do wonder if it has something to do with an interaction of the hardware on this  EP1. 
The generic ESP32s I have only have a light sensor and temp sensor configured on them, oh and they are used to manage some LED's converting 12v to 5v. Nothing fancy. 

So take my one example as a possibility that there could be something different about the EP1 config compared to just a default ESPhome installed that could be causing a conflict.

BTW, you stated 
"You could also try switching the framework to esp-idf rather than Arduino"
This is defined in your base configuration correct?  I don't define esp-idf in my snippet config.

BUT, I do have that in my esp32 configs for the hardware that I mentioned above.

```
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
     CONFIG_LWIP_IPV6_AUTOCONFIG: y
     CONFIG_LWIP_IPV6: "2"
     CONFIG_LWIP_IPV6_RDNSS_MAX_DNS_SERVERS: "2"
```
Thanks, keep up the good work I look forward to all of your hardware. I only really bought your hardware to support you and your channel and it really was not the end of the hardware did not work perfectly.

**Comment by EverythingSmartHome** [comment]
Yes it is most likely more prolific because the EP1 has a lot larger config than most devices and a lot more going on, so possibly rears it's head more. Bluetooth hasn't been enabled on the EP1 by default yet (but of course you are free to add it yourself as you have done) because there have been quite a lot of issues having BLE and WiFi active at the same time (not just on the EP1) and hence it was more reliable to leave it disabled by default and let users enable it if they wished.

Yes, the default framework on the EP1's (and indeed all ESPHome configs unless you specify otherwise like in your snippet above) is to use the Arduino Framework, but the ESP-IDF framework is more performant and seems to handle bluetooth and wifi at the same time much better. I would start with that first!

**Comment by isewise** [comment]
> BTW, you stated 
> "You could also try switching the framework to esp-idf rather than Arduino"
> This is defined in your base configuration correct?  I don't define esp-idf in my snippet config.
> 
> BUT, I do have that in my esp32 configs for the hardware that I mentioned above.
> 
> ```
> esp32:
>   board: esp32dev
>   framework:
>     type: esp-idf
>     sdkconfig_options:
>      CONFIG_LWIP_IPV6_AUTOCONFIG: y
>      CONFIG_LWIP_IPV6: "2"
>      CONFIG_LWIP_IPV6_RDNSS_MAX_DNS_SERVERS: "2"
> ```
> 
> 

I think what @pshempel is saying in his comment is that the configuration between esp-idf and Arduino is exposed in his configuration on his own ESP8266's. 

This configuration, between esp-idf & Arduino, is not available in the EP1's configuration.

**Comment by EverythingSmartHome** [comment]
That's because it's the non default option. I don't need to manually type out the framework settings for the EP1 because Arduino is the default option, where as if you want to change to esp-idf (like he did for the other device) then you need to specify it manually.

I'm also guessing your using the adopter/imported config and not the full one? If so then that option wouldn't show in the imported config even if it was defined in the main config (at least from memory)

**Comment by marcinwasilewski** [comment]
For the record: I haven't read this discussion entirely but mentioned having this issue in another thread. I'm not sure if this has something to do with esphome because if you link to github in the yaml config of your device you will inadvertently always update with the latest from this repository as well. So  you might think you are updating esphome but you might be updating two things at the same time. This is what happened to me.

I am still on the latest esphome (I couldn't find an easy way to downgrade it in home assistant) but I have downloaded version of EPO config from 2 weeks ago ([b56b71f2ae924af0ee2145df2d8a4864d0bb702b](https://github.com/EverythingSmartHome/everything-presence-one/blob/b56b71f2ae924af0ee2145df2d8a4864d0bb702b/everything-presence-one.yaml))  and sourced it locally. Now my device boots fine, and BLE also works as it did for the past couple of months.

I am using esp-idf.

**Comment by EverythingSmartHome** [comment]
Possibly but I don't see any changes that would cause it, all very minor. Though it's not impossible.

All of the reports I've had about this (Discord) came when people were already running the latest EP1 version, but updated to ESPHome 2023.12.6+. All were running Bluetooth proxy. I don't believe I've had any reports from users using the official config without modifications (which doesn't have Bluetooth enabled)

**Comment by marcinwasilewski** [comment]
Yeah, I had esp-idf, then after esphome update (and simultaneous update with the latest from this repo) my device started to go into bootloop. So I replaced with arduino, and it was back up again with the latest from the main branch, but then of course BLE stopped working. I needed BLE to operate my switchbot blinds so I started digging and wasn't able to downgrade ESPhome easily so I downgraded EPO instead, with the commit I linked to above. And then switched back to esp-idf. And now my EPO works, and my bluetooth blinds work.

**Comment by EverythingSmartHome** [comment]
Glad it's working for you now but I don't think it really indicates where the problem is since your not using the standard config. You also said you used the standard config and it worked other than Bluetooth not working (as it's not included) and then switched to esp-idf.

I'm also looking at this recently reported issue and wondering if it's related: https://github.com/esphome/issues/issues/5409

**Comment by marcinwasilewski** [comment]
My goal was just to share how I solved my problem, not to indicate to you where the problem is, but I think this extra information should be helpful because it narrows it down - the common denominator being the esp-idf

**Comment by EverythingSmartHome** [comment]
Absolutely, I appreciate the info and sorry if it didn't come across that way!

**Comment by stridger** [comment]
> I am still on the latest esphome (I couldn't find an easy way to downgrade it in home assistant) but I have downloaded version of EPO config from 2 weeks ago ([b56b71f2ae924af0ee2145df2d8a4864d0bb702b](https://github.com/EverythingSmartHome/everything-presence-one/blob/b56b71f2ae924af0ee2145df2d8a4864d0bb702b/everything-presence-one.yaml)) and sourced it locally.

Thank you very much for this! After going back to version 1.1.8 of this file, my EP1 Bluetooth Proxy also started working perfectly again, I was at a loss for the last 2 weeks or so.

I have hardcoded the version as follows for now in my ESPHome file:

`packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@1.1.8`

**Comment by alexolivier** [comment]
^ works for me too! Thanks for the tip

**Comment by hellcry37** [comment]
same here latest default cont with btproxy fails to work

**Comment by EverythingSmartHome** [comment]
> same here latest default cont with btproxy fails to work

Are you using the pre-built firmwares?

**Comment by stridger** [comment]
We obviously have to change the yaml file to enable bluetooth proxy, but apart from that just using the Git version, though now have to downgrade to 1.1.8 .

**Comment by EverythingSmartHome** [comment]
> We obviously have to change the yaml file to enable bluetooth proxy, but apart from that just using the Git version, though now have to downgrade to 1.1.8 .

You don't actually, pre-built configs were added to the installer for Bluetooth proxy already last week.

**Comment by hellcry37** [comment]
> > same here latest default cont with btproxy fails to work
> 
> Are you using the pre-built firmwares?

Yes, I've tried to flash my sensor with your default firmware: https://everythingsmarthome.github.io/everything-presence-one/updating.html

Selected HA, Bluetooth Proxy, Stable

As soon as this is done, does not boot anymore.

**Comment by EverythingSmartHome** [comment]
I'm not able to re-produce this on my side unfortunately. Can you verify if you get this after a complete power cycle (unplug and replug power cable after flashing)

**Comment by hellcry37** [comment]
> > > same here latest default cont with btproxy fails to work
> > 
> > 
> > Are you using the pre-built firmwares?
> 
> Yes, I've tried to flash my sensor with your default firmware: https://everythingsmarthome.github.io/everything-presence-one/updating.html
> 
> Selected HA, Bluetooth Proxy, Stable


The problem is fairly simple when I do all that is mentioned here device seems to work, except when you want to add it into ESPHOME, adopt it then the real mess begins.

Device gets adopted with this conf:
```yaml
substitutions:
  name: kitchen-epo
  friendly_name: Kitchen EPO
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: key_here

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
And that one has no bluetooth proxy! As soon as you update it you loose btproxy and if you change to a conf with btproxy then device stop working.

I've tried with this:
github://everythingsmarthome/presence-one/everything-presence-one-ble.yaml@main
github://everythingsmarthome/everything-presence-one/everything-presence-one-ble.yaml@main
