### ISSUE TITLE
mmWave led turning back on (randomly?)

### ISSUE THREAD

**Issue by poulti** [EverythingSmartHome/everything-presence-one#16]
Hello,

Great product, love the combined sensors in one box.
I have 3x EP1s in different rooms. I've turned all leds off (including mmWave) for all of them.
For some reasons, the mmWave led turns back on again randomly (didn't find the pattern/trigger yet). 
It doesn't happen to all 3 at the same time - but it happened to all 3 over time (hope it makes sense).
Any idea what it could come from? Any other idea to force it off?
Thanks

**Comment by EverythingSmartHome** [comment]
Hello!

Thanks! Have you got a screenshot of the history of the LED coming back on? Perhaps there is some sort of pattern to it?

Could it be an automation you have that turns on all lights in an area or something?

**Comment by poulti** [comment]
Hello,
Thanks for replying. 
I noticed when the led is back on (on the device) the mmWave led switch is still in "off" state. I have to tap the "on" lightning bolt and "off" again to turn it off. The history seems consistency as there is no visible "on" timeslots.
![mmwave_leds](https://user-images.githubusercontent.com/5324564/216605877-2a8f9ba8-d422-420a-9c85-3d01aaf0b12d.png)
I'll take note of the next event date/time to pin point it in the history, if that shows something.

2 out of 3 EP1s don't have any automation attached (yet), I just use them for the temp/hum/light sensors for now. But all 3 are affected (at different times)

**Comment by helicopterrun** [comment]
I also experienced this issue, but sure of the root cause. Since I don't need the lights for anything I just disabled them in the .yaml file.

**Comment by poulti** [comment]
Could you please detail what you changed in the config file?
Thanks

**Comment by helicopterrun** [comment]
Assuming you have the ESP Home add-on installed. You should be able to edit the "everything-presence-one.yaml" remove the "light:" code block as well as remove the led section from the "switch:" code block as shown:
```yaml
##### remove this block #####
#############################
#light:
#  - platform: status_led
#    name: "ESP32 Status LED"
#    pin: GPIO32
#    entity_category: config
#############################
## leave this block including "switch:" ##
switch:
  - platform: template
    name: "mmWave Sensor"
    id: "mmwave_sensor"
    entity_category: config
    optimistic: true
    restore_state: true
    turn_on_action:
      - uart.write: "sensorStart"
      - delay: 1s
    turn_off_action:
      - uart.write: "sensorStop"
      - delay: 1s

##### remove this block ##############
######################################
#  - platform: template
#    name: "mmWave LED"
#    id: "mmwave_led"
#    entity_category: config
#    optimistic: true
#    restore_state: true
#    turn_on_action:
#      - switch.turn_off: mmwave_sensor
#      - delay: 1s
#      - uart.write: "setLedMode 1 0"
#      - delay: 1s
#      - uart.write: "saveConfig"
#      - delay: 3s
#      - switch.turn_on: mmwave_sensor
#    turn_off_action:
#      - switch.turn_off: mmwave_sensor
#      - delay: 1s
#      - uart.write: "setLedMode 1 1"
#      - delay: 1s
#      - uart.write: "saveConfig"
#      - delay: 3s
#      - switch.turn_on: mmwave_sensor
######################################
end
```
Leave the rest of the code unchanged, validate and install the code.
