### ISSUE TITLE
Unable to Update to 2024.7.0 Failed Config Certification Verification

### ISSUE THREAD

**Issue by jwpine** [EverythingSmartHome/everything-presence-one#201]
I don't know if this is related to the breaking change that is mentioned in a different issue. However, I cannot update to 2024.7.0. If I try to update I get the following error. 

> INFO ESPHome 2024.7.0
> INFO Reading configuration /config/esphome/everything-presence-one-76384c.yaml...
> Failed config
> 
> http_request: [source /data/packages/405587a8/common/everything-presence-one-base.yaml:30]
>   
>   ESPHome supports certificate verification only via ESP-IDF. Set 'verify_ssl: false' to skip certificate validation and allow less secure HTTPS connections.
>   {}

my yaml file is below for reference:

```
substitutions:
  name: everything-presence-one-76384c
  friendly_name: Everything Presence One
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/everything-presence-one/everything-presence-one-sen0609-ble.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: redacted
esp32:
  board: esp32dev
  framework:
    type: arduino
#ota:
#  - platform: esphome

wifi:
  ssid: redacted
  password: redacted
```
