### ISSUE TITLE
Update Sensor shows new version - repo does not

### ISSUE THREAD

**Issue by dan-s-github** [EverythingSmartHome/everything-presence-one#224]
After updating my ep1 to version 1.2.5 I found an update notification for version 1.2.6

```
packages:
  Everything_Smart_Technology.Everything_Presence_One: 
    url: https://github.com/everythingsmarthome/everything-presence-one
    ref: 1.2.5
    file: everything-presence-one-ble.yaml
```

![image](https://github.com/user-attachments/assets/fd7ee033-4fba-4361-99b1-a80339ef886c)

This version is not an official release or tag on the repo.

![image](https://github.com/user-attachments/assets/f05172c8-015e-4bdf-b530-b88cd3453d68)

Is this intentional?
