### ISSUE TITLE
PIR false positives

### ISSUE THREAD

**Issue by golles** [EverythingSmartHome/everything-presence-one#230]
After yesterday's video, I wanted to give my EPOs another try, so I reinstalled 1 of them, and I'm still having the PIR sensor giving false positives.

This issue has been discussed before in #64 but that got closed without an actual fix.

Config:
```yaml
substitutions:
  name: epo-logeerkamer
  friendly_name: EPO Logeerkamer
packages:
  Everything Smart Technology.Everything Presence One: github://everythingsmarthome/everything-presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret epo_logeerkamer_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret epo_logeerkamer_static_ip
    gateway: !secret gateway
    subnet: !secret subnet

```

HA history:
<img width="1451" alt="Scherm­afbeelding 2024-11-29 om 23 03 48" src="https://github.com/user-attachments/assets/d754113b-f719-492a-8556-b9eff8af106a">

PIR false detections:
- 21:47
- 22:04
- 22:32
- 22:34
- 22:48
- 22:55
- 23:02

When both sensors detected occupancy, it was correct.
