### ISSUE TITLE
Xiaomi BLE devices appear and want to authenticate after reflashing and adding CO2 sensor to EP1 board v1.3

### ISSUE THREAD

**Issue by IanMajor12** [EverythingSmartHome/everything-presence-one#270]
After flashing and adding CO2 sensor to EP1 board v1.3 and adding Bluetooth at the same time, which then gives me the everything-presence-one-ble-co2-rev1.3.yaml

I now have a message in HA settings for Xiaomi BLE devices that appear and want to authenticate after flashing and adding CO2 sensor to EP1 board v1.3.  

It loops asking for a username and password or bind key, I've created a Xiaomi account but that doesn't seem to work for user/password.

If I delete the device and click okay then it seems to just be the battery info - which the EP1 has no battery so seems to be picking up some other device?

Here's my config:

```
substitutions:
  name: ep1-bedrooms
  friendly_name: ep1-bedrooms
packages:
  Everything Smart Technology.Everything Presence One: github://everythingsmarthome/everything-presence-one/everything-presence-one-ble-co2-rev1.3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 

bluetooth_proxy:
  active: True

esp32_ble_tracker:
    scan_parameters: 
      interval: 1100ms
      window: 1100ms 

```

Any help is appreciated.
