### ISSUE TITLE
mmWave Distance can't be set to set number

### ISSUE THREAD

**Issue by oneseventhree** [EverythingSmartHome/everything-presence-one#61]
Hi,

I ttry to change my value to 350cm's using:
```
service: number.set_value
data:
  value: "350"
target:
  entity_id: number.mmwave_distance
```

but it only goes to 345cm.

When I drag the slider it goes up 15cm incriments: 
345 to 360 to 375 to 390 etc

is there a way to change this to even 10cm or 5cm?

Thanks
