### ISSUE TITLE
Modifiable properties for temperature / humidity offset

### ISSUE THREAD

**Issue by liquidbrains** [EverythingSmartHome/everything-presence-one#74]
Hi.  

According to the documentation, via the Samsung integration, one can adjust the offsets for temp / humidity. I cannot find such properties on the HASS integration.  I think one can set that in substitutions, but that requires a rebuild / deploy.  

Would it be possible to have this as a property on the device configuration?

**Comment by EverythingSmartHome** [comment]
It's unfortunately possible at the moment as ESPHome does not support this, that's why the substitutions is required. Redeploying doesn't take too long so should be OK!

**Comment by liquidbrains** [comment]
Thanks for the reply.  Would it be possible to add documentation for the offset substitutions?  I'm still not certain I've done it correctly or if the weather has just changed and now it's reading a lower temperature.

**Comment by jfroy** [comment]
I have been experimenting with dynamic offsets using a template number and a lambda filter. Seems to work.

```yaml
sensor:
  - platform: shtcx
    temperature:
      name: "${room} Temperature"
      filters:
        - lambda: return x + id(temperature_offset).state;
    humidity:
      name: "${room} Humidity"
      filters:
        - lambda: return x + id(humidity_offset).state;
    address: 0x70
    update_interval: ${temperature_update_interval}

number:
  - platform: template
    name: Temperature offset
    id: temperature_offset
    entity_category: config
    min_value: -100.0
    max_value: 100.0
    initial_value: 0.0
    optimistic: true
    step: 0.1
    restore_value: true
    unit_of_measurement: "°C"
```
